export const LABEL_TRIBUNAL: Record<string, string> = {
  // Tribunais superiores
  STF: "STF — Supremo Tribunal Federal",
  STJ: "STJ — Superior Tribunal de Justiça",
  TST: "TST — Tribunal Superior do Trabalho",
  TSE: "TSE — Tribunal Superior Eleitoral",
  STM: "STM — Superior Tribunal Militar",

  // Tribunais Regionais Federais
  TRF1: "TRF1 — 1ª Região",
  TRF2: "TRF2 — 2ª Região (RJ/ES)",
  TRF3: "TRF3 — 3ª Região (SP/MS)",
  TRF4: "TRF4 — 4ª Região (RS/SC/PR)",
  TRF5: "TRF5 — 5ª Região (PE/AL/SE/RN/CE/PB)",
  TRF6: "TRF6 — 6ª Região (MG)",

  // Tribunais de Justiça estaduais
  TJAC: "TJAC — Acre",
  TJAL: "TJAL — Alagoas",
  TJAP: "TJAP — Amapá",
  TJAM: "TJAM — Amazonas",
  TJBA: "TJBA — Bahia",
  TJCE: "TJCE — Ceará",
  TJDFT: "TJDFT — Distrito Federal e Territórios",
  TJES: "TJES — Espírito Santo",
  TJGO: "TJGO — Goiás",
  TJMA: "TJMA — Maranhão",
  TJMT: "TJMT — Mato Grosso",
  TJMS: "TJMS — Mato Grosso do Sul",
  TJMG: "TJMG — Minas Gerais",
  TJPA: "TJPA — Pará",
  TJPB: "TJPB — Paraíba",
  TJPR: "TJPR — Paraná",
  TJPE: "TJPE — Pernambuco",
  TJPI: "TJPI — Piauí",
  TJRJ: "TJRJ — Rio de Janeiro",
  TJRN: "TJRN — Rio Grande do Norte",
  TJRS: "TJRS — Rio Grande do Sul",
  TJRO: "TJRO — Rondônia",
  TJRR: "TJRR — Roraima",
  TJSC: "TJSC — Santa Catarina",
  TJSP: "TJSP — São Paulo",
  TJSE: "TJSE — Sergipe",
  TJTO: "TJTO — Tocantins",

  // Tribunais Regionais do Trabalho
  TRT1: "TRT1 — 1ª Região (RJ)",
  TRT2: "TRT2 — 2ª Região (SP capital)",
  TRT3: "TRT3 — 3ª Região (MG)",
  TRT4: "TRT4 — 4ª Região (RS)",
  TRT5: "TRT5 — 5ª Região (BA)",
  TRT6: "TRT6 — 6ª Região (PE)",
  TRT7: "TRT7 — 7ª Região (CE)",
  TRT8: "TRT8 — 8ª Região (PA/AP)",
  TRT9: "TRT9 — 9ª Região (PR)",
  TRT10: "TRT10 — 10ª Região (DF/TO)",
  TRT11: "TRT11 — 11ª Região (AM/RR)",
  TRT12: "TRT12 — 12ª Região (SC)",
  TRT13: "TRT13 — 13ª Região (PB)",
  TRT14: "TRT14 — 14ª Região (RO/AC)",
  TRT15: "TRT15 — 15ª Região (SP interior)",
  TRT16: "TRT16 — 16ª Região (MA)",
  TRT17: "TRT17 — 17ª Região (ES)",
  TRT18: "TRT18 — 18ª Região (GO)",
  TRT19: "TRT19 — 19ª Região (AL)",
  TRT20: "TRT20 — 20ª Região (SE)",
  TRT21: "TRT21 — 21ª Região (RN)",
  TRT22: "TRT22 — 22ª Região (PI)",
  TRT23: "TRT23 — 23ª Região (MT)",
  TRT24: "TRT24 — 24ª Região (MS)",

  // Tribunais Regionais Eleitorais
  TREAC: "TRE-AC — Acre",
  TREAL: "TRE-AL — Alagoas",
  TREAP: "TRE-AP — Amapá",
  TREAM: "TRE-AM — Amazonas",
  TREBA: "TRE-BA — Bahia",
  TRECE: "TRE-CE — Ceará",
  TREDF: "TRE-DF — Distrito Federal",
  TREES: "TRE-ES — Espírito Santo",
  TREGO: "TRE-GO — Goiás",
  TREMA: "TRE-MA — Maranhão",
  TREMT: "TRE-MT — Mato Grosso",
  TREMS: "TRE-MS — Mato Grosso do Sul",
  TREMG: "TRE-MG — Minas Gerais",
  TREPA: "TRE-PA — Pará",
  TREPB: "TRE-PB — Paraíba",
  TREPR: "TRE-PR — Paraná",
  TREPE: "TRE-PE — Pernambuco",
  TREPI: "TRE-PI — Piauí",
  TRERJ: "TRE-RJ — Rio de Janeiro",
  TRERN: "TRE-RN — Rio Grande do Norte",
  TRERS: "TRE-RS — Rio Grande do Sul",
  TRERO: "TRE-RO — Rondônia",
  TRERR: "TRE-RR — Roraima",
  TRESC: "TRE-SC — Santa Catarina",
  TRESP: "TRE-SP — São Paulo",
  TRESE: "TRE-SE — Sergipe",
  TRETO: "TRE-TO — Tocantins",

  OUTRO: "Outro",
};

export const GRUPOS_TRIBUNAL: { label: string; opcoes: string[] }[] = [
  {
    label: "Tribunais Superiores",
    opcoes: ["STF", "STJ", "TST", "TSE", "STM"],
  },
  {
    label: "Tribunais Regionais Federais",
    opcoes: ["TRF1", "TRF2", "TRF3", "TRF4", "TRF5", "TRF6"],
  },
  {
    label: "Tribunais de Justiça",
    opcoes: [
      "TJAC", "TJAL", "TJAP", "TJAM", "TJBA", "TJCE", "TJDFT", "TJES",
      "TJGO", "TJMA", "TJMT", "TJMS", "TJMG", "TJPA", "TJPB", "TJPR",
      "TJPE", "TJPI", "TJRJ", "TJRN", "TJRS", "TJRO", "TJRR", "TJSC",
      "TJSP", "TJSE", "TJTO",
    ],
  },
  {
    label: "Tribunais Regionais do Trabalho",
    opcoes: [
      "TRT1", "TRT2", "TRT3", "TRT4", "TRT5", "TRT6", "TRT7", "TRT8",
      "TRT9", "TRT10", "TRT11", "TRT12", "TRT13", "TRT14", "TRT15",
      "TRT16", "TRT17", "TRT18", "TRT19", "TRT20", "TRT21", "TRT22",
      "TRT23", "TRT24",
    ],
  },
  {
    label: "Tribunais Regionais Eleitorais",
    opcoes: [
      "TREAC", "TREAL", "TREAP", "TREAM", "TREBA", "TRECE", "TREDF",
      "TREES", "TREGO", "TREMA", "TREMT", "TREMS", "TREMG", "TREPA",
      "TREPB", "TREPR", "TREPE", "TREPI", "TRERJ", "TRERN", "TRERS",
      "TRERO", "TRERR", "TRESC", "TRESP", "TRESE", "TRETO",
    ],
  },
  {
    label: "Outro",
    opcoes: ["OUTRO"],
  },
];

export const TODOS_TRIBUNAIS = Object.keys(LABEL_TRIBUNAL);
